### ISSUE TITLE
Externally Hosted Images

### ISSUE THREAD

**Issue by carlpeaslee** [artsmia/mia-storytelling#21]
First a note on the way Knight Lab does it with Gigapixel images –– they say, "You just have to give us a url where your image tiles are hosted. Here is how you create tiles. Here is how you upload them to a server." This is also an option we could use –– it would be really easy to implement but I think its kind of user-unfriendly.

I might have a different solution using google drives. Let me know what you all think about this:

1. The user **must** authenticate with a google account otherwise they can't upload images.
2. When they upload an image, that image is sent to our servers to be turned into tiles.
3. Those tiles are then uploaded to a directory on the user's google drive. 
4. We store the url of that directory in our database.

Pros:
-We are not hosting any of the images
-Most users are familiar with google drive

Cons:
-If a user messes with the file, it won't work on our site anymore 
-Images will be stored to individual user accounts,  not on an organization wide account

**Comment by carlpeaslee** [comment]
I should also make sure I mention that there would be another more advanced option using S3 where an organization's admin would specify an S3 bucket and give us an access token and we'd just use their S3 bucket. 

The only hard part about this is that only a tech savvy person would have an S3 account and know how to give us an access token to it.

**Comment by kjell** [comment]
At one point we talked about simply hosting the images - upload them to us and we do the rest. At least for now it probably won't amount to that much, and we can get an idea for cost as we go. Long term we could calculate of storage/hosting costs on our own S3 account per user/organization and pass on the cost or suggest a minimal donation for orgs that are using the platform heavily?

**Comment by mtongen** [comment]
@kjell - It's less about the cost and more about the liability (image rights) and maintenance responsibilities. I think @carlpeaslee and @ghalver have mapped out some promising options, so let's continue to explore that.

**Comment by carlpeaslee** [comment]
@mtongen –– I think you're right that using google would probably help to mitigate image rights liability since we would never actually be hosting any images but I'm not completely sold that it will reduce maintenance responsibilities.

What are some of the specific maintenance concerns that we have?

**Comment by kjell** [comment]
I don't get the difference in us hosting an image versus google hosting it. Either way the image is out of the proverbial bag.

**Comment by carlpeaslee** [comment]
ok, I got image hosting working with google drives. So now users can upload files and we tile the images and then put them on the users google drive. I'm going to smooth out the process and hopefully you all will be able to give it a shot tomorrow.

**Comment by carlpeaslee** [comment]
After talking with some stakeholders, we resolved to keep things hosted by us through S3. The google functionality is still in the application and we can adapt it for something else.
